services:
  - type: web
    name: transferencia-de-calor
    runtime: python
    buildCommand: |
      # 1. Instalar dependencias del frontend y compilar
      cd transferencia-de-calor-frontend
      npm install
      npm run build
      cd ..
      # 2. Copiar el build del frontend a la carpeta static del backend
      rm -rf transferencia-de-calor-backend/static
      cp -r transferencia-de-calor-frontend/dist transferencia-de-calor-backend/static
      # 3. Instalar dependencias de python
      cd transferencia-de-calor-backend
      pip install -r requirements.txt
    startCommand: |
      cd transferencia-de-calor-backend
      gunicorn --bind 0.0.0.0:$PORT --timeout 600 --worker-class uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 10000
